packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@sentry-internal/node-cpu-profiler'
  - '@swc/core'
  - '@vercel/speed-insights'
  - argon2
  - lefthook
  - prisma
  - puppeteer
  - sharp
  - unrs-resolver
