###
# Meta Service Test - Notion 페이지 메타 정보 추출 테스트
#
# 이 파일은 Notion 페이지의 twitter:title과 twitter:image(og:title, og:image)를
# 추출하는 메타 서비스를 테스트합니다.
###

@baseUrl = http://localhost:9999

### 1. Notion 페이지 메타 정보 추출 - 예시 1
# @name getNotionMeta1
GET {{baseUrl}}/v1/projects?url=https://www.notion.so/UMC-7th-Workbook-b88ca01ab2894819b1c8ca87ea28de93

###

### 2. Notion 페이지 메타 정보 추출 - 예시 2 (다른 Notion 페이지)
# @name getNotionMeta2
GET {{baseUrl}}/v1/projects?url=https://grounded-camel-81a.notion.site/Node-js-1650c26e28568047b13ec6bbca2e11a7

###

### 3. 일반 웹사이트 메타 정보 추출 (비교용)
# @name getRegularWebsiteMeta
GET {{baseUrl}}/v1/projects?url=https://github.com

###

### 4. Notion Site 도메인 테스트
# @name getNotionSiteMeta
GET {{baseUrl}}/v1/projects?url=https://teamsparta.notion.site/Node-js-1650c26e28568047b13ec6bbca2e11a7

###

### 5. 커스텀 Notion URL 테스트 (실제 사용할 URL로 변경하세요)
# @name getCustomNotionMeta
GET {{baseUrl}}/v1/projects?url=YOUR_NOTION_PAGE_URL_HERE

###

